// Code generated by goyacc -o y.go parse.y. DO NOT EDIT.

//line parse.y:2
package parser

import __yyfmt__ "fmt"

//line parse.y:2

//line parse.y:5
type yySymType struct {
	yys   int
	stmt  Statement
	stmts []Statement

	selectStmt *SelectStatement

	field   *Field
	fields  Fields
	source  *Source
	sources Sources
	expr    *ExprNode

	str     string
	int     int
	int64   int64
	float64 float64
	bool    bool
}

const SELECT = 57346
const FROM = 57347
const WHERE = 57348
const AS = 57349
const GROUP = 57350
const BY = 57351
const ORDER = 57352
const LIMIT = 57353
const CREATE = 57354
const UPDATE = 57355
const INSERT = 57356
const INTO = 57357
const DELETE = 57358
const STAR = 57359
const EQ = 57360
const NEQ = 57361
const LT = 57362
const LTE = 57363
const GT = 57364
const GTE = 57365
const LEFTC = 57366
const RIGHTC = 57367
const NAME = 57368
const INTEGER = 57369
const FLOAT = 57370
const STRING = 57371
const COMMA = 57372
const SEMICOLON = 57373
const OR = 57374
const AND = 57375
const ADD = 57376
const DEC = 57377
const TIME = 57378
const DIV = 57379
const MOD = 57380

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SELECT",
	"FROM",
	"WHERE",
	"AS",
	"GROUP",
	"BY",
	"ORDER",
	"LIMIT",
	"CREATE",
	"UPDATE",
	"INSERT",
	"INTO",
	"DELETE",
	"STAR",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"LEFTC",
	"RIGHTC",
	"NAME",
	"INTEGER",
	"FLOAT",
	"STRING",
	"COMMA",
	"SEMICOLON",
	"OR",
	"AND",
	"ADD",
	"DEC",
	"TIME",
	"DIV",
	"MOD",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parse.y:167

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 50

var yyAct = [...]int8{
	40, 29, 28, 28, 22, 20, 19, 29, 28, 21,
	5, 23, 25, 26, 24, 23, 25, 26, 24, 9,
	12, 32, 33, 34, 35, 36, 37, 30, 8, 13,
	15, 6, 18, 1, 38, 39, 41, 11, 4, 10,
	31, 17, 14, 7, 16, 3, 2, 0, 0, 27,
}

var yyPact = [...]int16{
	34, -1000, -21, -1000, 2, 34, 32, -10, -1000, -1000,
	-1000, 4, 2, 26, -24, -1000, -1000, -1000, -15, 4,
	-31, -15, 3, -1000, -1000, -1000, -1000, -1000, -15, -15,
	-25, -11, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -30,
	-1000, -1000,
}

var yyPgo = [...]int8{
	0, 33, 46, 45, 43, 31, 42, 29, 5, 41,
	4, 40,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 2, 3, 5, 5, 4, 4,
	7, 7, 6, 9, 9, 8, 8, 8, 8, 11,
	11, 11, 11, 11, 11, 10, 10, 10, 10,
}

var yyR2 = [...]int8{
	0, 1, 2, 3, 1, 5, 1, 3, 1, 1,
	1, 3, 1, 2, 0, 3, 3, 3, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 4, 31, -5, -4, 26, 17,
	-1, 5, 30, -7, -6, 26, -5, -9, 6, 30,
	-8, 24, -10, 26, 29, 27, 28, -7, 33, 32,
	-8, -11, 18, 19, 20, 21, 22, 23, -8, -8,
	25, -10,
}

var yyDef = [...]int8{
	0, -2, 1, 4, 0, 2, 0, 6, 8, 9,
	3, 0, 0, 14, 10, 12, 7, 5, 0, 0,
	13, 0, 0, 25, 26, 27, 28, 11, 0, 0,
	0, 0, 19, 20, 21, 22, 23, 24, 17, 18,
	15, 16,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:56
		{
			yylex.(*Lexer).AppendStmt(yyDollar[1].stmt)
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parse.y:59
		{
			yylex.(*Lexer).AppendStmt(yyDollar[1].stmt)
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parse.y:62
		{
			yylex.(*Lexer).AppendStmt(yyDollar[1].stmt)
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:67
		{
			yyVAL.stmt = yyDollar[1].selectStmt
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parse.y:72
		{
			sele := &SelectStatement{
				Fields:         yyDollar[2].fields,
				Sources:        yyDollar[4].sources,
				WhereCondition: yyDollar[5].expr,
			}

			yyVAL.selectStmt = sele
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:83
		{
			yyVAL.fields = []*Field{yyDollar[1].field}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parse.y:86
		{
			yyVAL.fields = append(yyDollar[3].fields, yyDollar[1].field)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:91
		{
			yyVAL.field = &Field{Name: yyDollar[1].str}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:94
		{
			yyVAL.field = &Field{Name: yyDollar[1].str}
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:99
		{
			yyVAL.sources = []*Source{yyDollar[1].source}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parse.y:102
		{
			yyVAL.sources = append(yyDollar[3].sources, yyDollar[1].source)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:107
		{
			yyVAL.source = &Source{Name: yyDollar[1].str}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parse.y:112
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 14:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parse.y:115
		{
			yyVAL.expr = nil
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parse.y:120
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parse.y:123
		{
			yyVAL.expr = &ExprNode{Type: BinaryNode, Left: yyDollar[1].expr, Op: yyDollar[2].int, Right: yyDollar[3].expr}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parse.y:126
		{
			yyVAL.expr = &ExprNode{Type: BinaryNode, Left: yyDollar[1].expr, Op: yyDollar[2].int, Right: yyDollar[3].expr}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parse.y:129
		{
			yyVAL.expr = &ExprNode{Type: BinaryNode, Left: yyDollar[1].expr, Op: yyDollar[2].int, Right: yyDollar[3].expr}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:134
		{
			yyVAL.int = yyDollar[1].int
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:137
		{
			yyVAL.int = yyDollar[1].int
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:140
		{
			yyVAL.int = yyDollar[1].int
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:143
		{
			yyVAL.int = yyDollar[1].int
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:146
		{
			yyVAL.int = yyDollar[1].int
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:149
		{
			yyVAL.int = yyDollar[1].int
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:154
		{
			yyVAL.expr = &ExprNode{Type: FieldNode, Name: yyDollar[1].str}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:157
		{
			yyVAL.expr = &ExprNode{Type: StringNode, StrVal: yyDollar[1].str}
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:160
		{
			yyVAL.expr = &ExprNode{Type: IntegerNode, IntVal: yyDollar[1].int64}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parse.y:163
		{
			yyVAL.expr = &ExprNode{Type: FloatNode, FloVal: yyDollar[1].float64}
		}
	}
	goto yystack /* stack new state and value */
}
